#!/usr/bin/env python3
"""Second batch: match cards, tooltips, abbr labels."""

from pathlib import Path

REPORT = Path(__file__).parent.parent / "wc_june16_2026_report.html"

REPLACEMENTS = [
    # France data snapshot lines
    (
        ' FRA Maignan; Koundé/Saliba/Upamecano/Digne; Tchouaméni/Rabiot; Olise/Dembélé/Doué/Mbappé. SEN Mendy; Diatta/Koulibaly/Niakhaté/Jakobs; Camara/Sarr; Mané/Jackson/Ndiaye. (ESPN, Sports Mole, RotoWire, L\'Équipe ~Jun 14-15)</div>',
        ' <span class="en">FRA Maignan; Koundé/Saliba/Upamecano/Digne; Tchouaméni/Rabiot; Olise/Dembélé/Doué/Mbappé. SEN Mendy; Diatta/Koulibaly/Niakhaté/Jakobs; Camara/Sarr; Mané/Jackson/Ndiaye. (ESPN, Sports Mole, RotoWire, L\'Équipe ~Jun 14-15)</span><span class="es">FRA Maignan; Koundé/Saliba/Upamecano/Digne; Tchouaméni/Rabiot; Olise/Dembélé/Doué/Mbappé. SEN Mendy; Diatta/Koulibaly/Niakhaté/Jakobs; Camara/Sarr; Mané/Jackson/Ndiaye. (ESPN, Sports Mole, RotoWire, L\'Équipe ~14-15 Jun)</span></div>',
    ),
    (
        ' FRA Koundé muscular monitor (expected); SEN no major. (Multi-source consistent)</div>',
        ' <span class="en">FRA Koundé muscular monitor (expected); SEN no major. (Multi-source consistent)</span><span class="es">FRA Koundé monitor muscular (esperado); SEN sin lesiones mayores. (Consistente multi-fuente)</span></div>',
    ),
    (
        ' FRA 2063 / SEN 1860 (finisher pair bonus applied)</div>',
        ' <span class="en">FRA 2063 / SEN 1860 (finisher pair bonus applied)</span><span class="es">FRA 2063 / SEN 1860 (bono par de goleadores aplicado)</span></div>',
    ),
    (
        ' 2002 0-1 SEN shock precedent. FRA warmups mixed. SEN counter-capable.</div>',
        ' <span class="en">2002 0-1 SEN shock precedent. FRA warmups mixed. SEN counter-capable.</span><span class="es">Precedente shock SEN 0-1 en 2002. Calentamientos FRA mixtos. SEN capaz de contraataque.</span></div>',
    ),
    # France model + recommendations
    (
        '<div class="text-xs mt-2"><span class="abbr">λ<span class="tooltip">λ (lambda) = the expected number of goals a team is projected to score in this match according to the model.</span></span> 2.31/0.24 • <span class="abbr">P(O2.5)<span class="tooltip">P(O2.5) = Probability of Over 2.5 goals (3 or more total goals in the match).</span></span> 46.9% • <span class="abbr">DC FRA+O3.5 joint<span class="tooltip">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span></span> 0.258–0.271 (enhanced)</div>',
        '<div class="text-xs mt-2"><span class="abbr">λ<span class="tooltip"><span class="en">λ (lambda) = the expected number of goals a team is projected to score in this match according to the model.</span><span class="es">λ (lambda) = número esperado de goles que un equipo proyecta marcar según el modelo.</span></span></span> 2.31/0.24 • <span class="abbr">P(O2.5)<span class="tooltip"><span class="en">P(O2.5) = Probability of Over 2.5 goals (3 or more total goals in the match).</span><span class="es">P(O2.5) = Probabilidad de Más de 2,5 goles (3 o más goles totales en el partido).</span></span></span> 46.9% • <span class="abbr"><span class="en">DC FRA+O3.5 joint</span><span class="es">Junta DC FRA+O3.5</span><span class="tooltip"><span class="en">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span><span class="es">Es una apuesta combinada: Francia debe ganar el partido Y debe haber más de 3,5 goles totales (4 o más goles por ambos equipos combinados). La junta DC significa que usamos un modelo de probabilidad correlacionada (Dixon-Coles) en lugar de simplemente multiplicar las dos probabilidades separadas.</span></span></span> <span class="en">0.258–0.271 (enhanced)</span><span class="es">0,258–0,271 (mejorado)</span></div>',
    ),
    (
        '<div class="text-xs text-rose-400 mt-1">Prior screenshot FRA win ~1.50–1.52 → ~0/neg EV (Pass). FRA+O3.5 boost 5.15 context → +33% raw but <span class="abbr">HALT<span class="tooltip">HALT means our rules say "stop and double-check with extra sharp data before considering this bet" if the model EV looks too good to be true — usually above +25%.</span></span> per Rules 13/18. <span class="text-xs text-slate-400">(Newbie: "HALT" means our rules say "stop and double-check with extra sharp data before considering this bet" if the model EV looks too good to be true — usually above +25%. "Rules 13/18" are specific safety checks in our betting analysis protocol.)</span></div>',
        '<div class="text-xs text-rose-400 mt-1"><span class="en">Prior screenshot FRA win ~1.50–1.52 → ~0/neg EV (Pass). FRA+O3.5 boost 5.15 context → +33% raw but</span><span class="es">Captura previa victoria FRA ~1,50–1,52 → ~0/EV neg (Pass). Boost FRA+O3.5 contexto 5,15 → +33% raw pero</span> <span class="abbr">HALT<span class="tooltip"><span class="en">HALT means our rules say "stop and double-check with extra sharp data before considering this bet" if the model EV looks too good to be true — usually above +25%.</span><span class="es">HALT significa que nuestras reglas dicen "detente y verifica con datos sharp extra antes de considerar esta apuesta" si el EV del modelo parece demasiado bueno — usualmente por encima de +25%.</span></span></span> <span class="en">per Rules 13/18.</span><span class="es">según Reglas 13/18.</span> <span class="text-xs text-slate-400">(<span class="en">Newbie: "HALT" means our rules say "stop and double-check with extra sharp data before considering this bet" if the model EV looks too good to be true — usually above +25%. "Rules 13/18" are specific safety checks in our betting analysis protocol.</span><span class="es">Principiante: "HALT" significa que nuestras reglas dicen "detente y verifica con datos sharp extra" si el EV parece demasiado bueno — usualmente por encima de +25%. "Reglas 13/18" son verificaciones de seguridad específicas en nuestro protocolo de análisis.</span>)</span></div>',
    ),
    (
        '<div class="p-2 bg-emerald-950/60 border border-emerald-900 rounded"><strong>1. <span class="abbr">FRA win + Over 3.5<span class="tooltip">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span></span> (if boost visible &amp; HALT drilldown clears)</strong> — DC joint 0.258–0.271, fair ~3.7–3.9. <span class="abbr">MOD<span class="tooltip">MODERATE = A bet with solid positive expected value that is reasonably robust across different assumptions.</span></span> if cleared. Risks: 2002 upset, rotation, low-block. Single failure: Mbappé variance. Conf 50%.</div>',
        '<div class="p-2 bg-emerald-950/60 border border-emerald-900 rounded"><strong>1. <span class="abbr"><span class="en">FRA win + Over 3.5</span><span class="es">Victoria FRA + Más 3.5</span><span class="tooltip"><span class="en">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span><span class="es">Es una apuesta combinada: Francia debe ganar el partido Y debe haber más de 3,5 goles totales (4 o más goles por ambos equipos combinados). La junta DC usa un modelo correlacionado (Dixon-Coles) en lugar de multiplicar las probabilidades separadas.</span></span></span> <span class="en">(if boost visible &amp; HALT drilldown clears)</span><span class="es">(si boost visible y drilldown HALT despeja)</span></strong> <span class="en">— DC joint 0.258–0.271, fair ~3.7–3.9.</span><span class="es">— Junta DC 0,258–0,271, justa ~3,7–3,9.</span> <span class="abbr">MOD<span class="tooltip"><span class="en">MODERATE = A bet with solid positive expected value that is reasonably robust across different assumptions.</span><span class="es">MODERADO = Apuesta con EV positivo sólido y razonablemente robusta entre distintos supuestos.</span></span></span> <span class="en">if cleared. Risks: 2002 upset, rotation, low-block. Single failure: Mbappé variance. Conf 50%.</span><span class="es">si se despeja. Riesgos: upset 2002, rotación, bloque bajo. Falla única: varianza Mbappé. Conf 50%.</span></div>',
    ),
    (
        '<div class="p-2 bg-slate-950 border border-slate-800 rounded"><strong>2. <span class="abbr">Under 2.5<span class="tooltip">Under 2.5 goals means the total goals by both teams in the full match will be 2 or fewer (0, 1, or 2 goals total).</span></span> / <span class="abbr">BTTS No<span class="tooltip">BTTS No = Both Teams To Score No. At least one team fails to score any goals.</span></span></strong> (data-aligned if o favorable) — Mismatch + quality gap supports low totals. <span class="abbr">SPEC<span class="tooltip">SPECULATIVE = A bet with positive expected value but more sensitive to assumptions or higher variance; smaller recommended stakes.</span></span> if screenshot value.</div>',
        '<div class="p-2 bg-slate-950 border border-slate-800 rounded"><strong>2. <span class="abbr"><span class="en">Under 2.5</span><span class="es">Menos 2.5</span><span class="tooltip"><span class="en">Under 2.5 goals means the total goals by both teams in the full match will be 2 or fewer (0, 1, or 2 goals total).</span><span class="es">Menos 2.5 goles significa que el total de goles de ambos equipos en el partido completo será 2 o menos (0, 1 o 2 goles totales).</span></span></span> / <span class="abbr"><span class="en">BTTS No</span><span class="es">BTTS No</span><span class="tooltip"><span class="en">BTTS No = Both Teams To Score No. At least one team fails to score any goals.</span><span class="es">BTTS No = Ambos Equipos Marcan No. Al menos un equipo no anota ningún gol.</span></span></span></strong> <span class="en">(data-aligned if o favorable) — Mismatch + quality gap supports low totals.</span><span class="es">(alineado con datos si o favorable) — Desajuste + brecha de calidad favorece totales bajos.</span> <span class="abbr">SPEC<span class="tooltip"><span class="en">SPECULATIVE = A bet with positive expected value but more sensitive to assumptions or higher variance; smaller recommended stakes.</span><span class="es">ESPECULATIVO = Apuesta con EV positivo pero más sensible a supuestos o mayor varianza; stakes recomendados menores.</span></span></span> <span class="en">if screenshot value.</span><span class="es">si hay valor en captura.</span></div>',
    ),
    (
        '<div class="p-2 bg-rose-950/40 border border-rose-900 rounded"><strong>3. <span class="abbr">FRA 1X2<span class="tooltip">1X2 is the basic three-way bet: pick France to win (1), the match to draw (X), or Senegal to win (2).</span></span> heavy short</strong> — Negative EV after Rule 14 + bias. <strong><span class="abbr">Pass<span class="tooltip">PASS = This bet does not show positive expected value or fails our robustness checks; we recommend skipping it.</span></span></strong>.</div>',
        '<div class="p-2 bg-rose-950/40 border border-rose-900 rounded"><strong>3. <span class="abbr"><span class="en">FRA 1X2</span><span class="es">FRA 1X2</span><span class="tooltip"><span class="en">1X2 is the basic three-way bet: pick France to win (1), the match to draw (X), or Senegal to win (2).</span><span class="es">1X2 es la apuesta básica de tres vías: elige victoria de Francia (1), empate (X) o victoria de Senegal (2).</span></span></span> <span class="en">heavy short</span><span class="es">corto pesado</span></strong> <span class="en">— Negative EV after Rule 14 + bias.</span><span class="es">— EV negativo tras Regla 14 + sesgo.</span> <strong><span class="abbr"><span class="en">Pass</span><span class="es">Pass</span><span class="tooltip"><span class="en">PASS = This bet does not show positive expected value or fails our robustness checks; we recommend skipping it.</span><span class="es">PASS = Esta apuesta no muestra EV positivo o falla nuestras verificaciones de robustez; recomendamos omitirla.</span></span></span></strong>.</div>',
    ),
    # Iraq card
    (
        '<div>NOR full strength (Haaland + Sørloth = finisher-pair +30 Elo). IRQ domestic-heavy squad. Elo NOR 1914 / IRQ 1607. No major injuries.</div>',
        '<div><span class="en">NOR full strength (Haaland + Sørloth = finisher-pair +30 Elo). IRQ domestic-heavy squad. Elo NOR 1914 / IRQ 1607. No major injuries.</span><span class="es">NOR plena fuerza (Haaland + Sørloth = par de goleadores +30 Elo). IRQ plantilla mayormente doméstica. Elo NOR 1914 / IRQ 1607. Sin lesiones mayores.</span></div>',
    ),
    (
        '<div class="text-xs text-rose-400 mt-1">Prior 1.19 NOR win → −24% EV. <strong><span class="abbr">Pass<span class="tooltip">PASS = This bet does not show positive expected value or fails our robustness checks; we recommend skipping it.</span></span></strong>. DC boost 5.20 context → high raw but <span class="abbr">SENSITIVE<span class="tooltip">SENSITIVE = The bet shows positive EV only under some assumptions (e.g. base case) but not others (conservative or aggressive); treat with caution and use smaller stakes.</span></span>.</div>',
        '<div class="text-xs text-rose-400 mt-1"><span class="en">Prior 1.19 NOR win → −24% EV.</span><span class="es">Previo 1,19 victoria NOR → −24% EV.</span> <strong><span class="abbr"><span class="en">Pass</span><span class="es">Pass</span><span class="tooltip"><span class="en">PASS = This bet does not show positive expected value or fails our robustness checks; we recommend skipping it.</span><span class="es">PASS = Esta apuesta no muestra EV positivo o falla nuestras verificaciones; recomendamos omitirla.</span></span></span></strong>. <span class="en">DC boost 5.20 context → high raw but</span><span class="es">Boost DC contexto 5,20 → raw alto pero</span> <span class="abbr">SENSITIVE<span class="tooltip"><span class="en">SENSITIVE = The bet shows positive EV only under some assumptions (e.g. base case) but not others (conservative or aggressive); treat with caution and use smaller stakes.</span><span class="es">SENSIBLE = La apuesta muestra EV positivo solo bajo algunos supuestos; tratar con cautela y stakes menores.</span></span></span>.</div>',
    ),
    (
        '<div class="text-xs">1. IRQ or Draw DC (SPEC if boost visible &amp; cleared) — 35.6% uplifted. Cap S/15. Risks: NOR clinical. 2. High totals / NOR scoring (finisher edge). 3. NOR 1X2 heavy short → Pass.</div>',
        '<div class="text-xs"><span class="en">1. IRQ or Draw DC (SPEC if boost visible &amp; cleared) — 35.6% uplifted. Cap S/15. Risks: NOR clinical. 2. High totals / NOR scoring (finisher edge). 3. NOR 1X2 heavy short → Pass.</span><span class="es">1. IRQ o Empate DC (SPEC si boost visible y despejado) — 35,6% con uplift. Tope S/15. Riesgos: NOR clínico. 2. Totales altos / NOR anotando (ventaja goleadores). 3. NOR 1X2 corto pesado → Pass.</span></div>',
    ),
    # Argentina card
    (
        '<div class="font-medium mb-1">Data</div>',
        '<div class="font-medium mb-1"><span class="en">Data</span><span class="es">Datos</span></div>',
    ),
    (
        '<div>ARG strong core (Messi confirmed, Alvarez fit). ALG organized (4 CS streak discounted — low-quality opp). Bensebaini out. Elo ARG 2115 (finisher bonus) / ALG 1772. λ ARG 2.51 / ALG 0.09 extreme.</div>',
        '<div><span class="en">ARG strong core (Messi confirmed, Alvarez fit). ALG organized (4 CS streak discounted — low-quality opp). Bensebaini out. Elo ARG 2115 (finisher bonus) / ALG 1772. λ ARG 2.51 / ALG 0.09 extreme.</span><span class="es">ARG núcleo fuerte (Messi confirmado, Alvarez en forma). ALG organizada (racha 4 CS descontada — rival de baja calidad). Bensebaini fuera. Elo ARG 2115 (bono goleador) / ALG 1772. λ ARG 2,51 / ALG 0,09 extremo.</span></div>',
    ),
    (
        '<div>pARG 74% / pD 19.8% / pALG 6.2%. <span class="abbr">DC ARG+BTTS joint<span class="tooltip">DC ARG+BTTS joint = Correlated probability that Argentina wins AND both teams score at least one goal. The model shows this is very unlikely (extreme mismatch means Algeria rarely scores).</span></span> only 0.069 (extreme mismatch).</div>',
        '<div><span class="en">pARG 74% / pD 19.8% / pALG 6.2%.</span><span class="es">pARG 74% / pD 19,8% / pALG 6,2%.</span> <span class="abbr"><span class="en">DC ARG+BTTS joint</span><span class="es">Junta DC ARG+BTTS</span><span class="tooltip"><span class="en">DC ARG+BTTS joint = Correlated probability that Argentina wins AND both teams score at least one goal. The model shows this is very unlikely (extreme mismatch means Algeria rarely scores).</span><span class="es">Junta DC ARG+BTTS = Probabilidad correlacionada de que Argentina gane Y ambos equipos marquen al menos un gol. El modelo muestra que es muy improbable (desajuste extremo significa que Argelia rara vez anota).</span></span></span> <span class="en">only 0.069 (extreme mismatch).</span><span class="es">solo 0,069 (desajuste extremo).</span></div>',
    ),
    (
        '<div class="text-xs text-rose-400 mt-1">Prior 1.41 ARG win → neg EV. ARG+BTTS @4.45 → −69.5% (DC joint). <strong><span class="abbr">Pass<span class="tooltip">PASS = This bet does not show positive expected value or fails our robustness checks; we recommend skipping it.</span></span></strong>.</div>',
        '<div class="text-xs text-rose-400 mt-1"><span class="en">Prior 1.41 ARG win → neg EV. ARG+BTTS @4.45 → −69.5% (DC joint).</span><span class="es">Previo 1,41 victoria ARG → EV neg. ARG+BTTS @4,45 → −69,5% (junta DC).</span> <strong><span class="abbr"><span class="en">Pass</span><span class="es">Pass</span><span class="tooltip"><span class="en">PASS = This bet does not show positive expected value or fails our robustness checks; we recommend skipping it.</span><span class="es">PASS = Esta apuesta no muestra EV positivo o falla nuestras verificaciones; recomendamos omitirla.</span></span></span></strong>.</div>',
    ),
    (
        '<div class="text-xs">1. ARG win 1X2 — neg EV. Pass. 2. Over 2.5 or high-quality scorer props (if o ≥3.00) — P(O2.5) 48.2%. SPEC if screenshot value (Messi fit). 3. ARG+BTTS boost — extreme mismatch makes BTTS rare. Pass.</div>',
        '<div class="text-xs"><span class="en">1. ARG win 1X2 — neg EV. Pass. 2. Over 2.5 or high-quality scorer props (if o ≥3.00) — P(O2.5) 48.2%. SPEC if screenshot value (Messi fit). 3. ARG+BTTS boost — extreme mismatch makes BTTS rare. Pass.</span><span class="es">1. Victoria ARG 1X2 — EV neg. Pass. 2. Más 2.5 o props de goleador de calidad (si o ≥3,00) — P(O2.5) 48,2%. SPEC si valor en captura (Messi en forma). 3. Boost ARG+BTTS — desajuste extremo hace BTTS raro. Pass.</span></div>',
    ),
    # Austria card
    (
        '<div>AUT: Baumgartner out (creativity loss), Alaba fit caveat, Wimmer doubts. XI Schlager; Laimer/Lienhart/Alaba/Mwene; X.Schlager/Seiwald; Sabitzer/Schmid/Gregoritsch; Arnautović. JOR low-block (Sellami/Morocco-2022 style) but missing key striker. Elo AUT 1830 / JOR 1680. Milder weather supports organized underdog.</div>',
        '<div><span class="en">AUT: Baumgartner out (creativity loss), Alaba fit caveat, Wimmer doubts. XI Schlager; Laimer/Lienhart/Alaba/Mwene; X.Schlager/Seiwald; Sabitzer/Schmid/Gregoritsch; Arnautović. JOR low-block (Sellami/Morocco-2022 style) but missing key striker. Elo AUT 1830 / JOR 1680. Milder weather supports organized underdog.</span><span class="es">AUT: Baumgartner fuera (pérdida de creatividad), reserva forma de Alaba, dudas Wimmer. XI Schlager; Laimer/Lienhart/Alaba/Mwene; X.Schlager/Seiwald; Sabitzer/Schmid/Gregoritsch; Arnautović. JOR bloque bajo (estilo Sellami/Marruecos-2022) pero sin delantero clave. Elo AUT 1830 / JOR 1680. Clima más templado favorece al underdog organizado.</span></div>',
    ),
    (
        '<div>pAUT 60.1% / pD 23.2% / pJOR 16.7% (λ 2.07/0.38). Fair draw ~4.31.</div>',
        '<div><span class="en">pAUT 60.1% / pD 23.2% / pJOR 16.7% (λ 2.07/0.38). Fair draw ~4.31.</span><span class="es">pAUT 60,1% / pD 23,2% / pJOR 16,7% (λ 2,07/0,38). Empate justo ~4,31.</span></div>',
    ),
    (
        '<div class="text-xs text-emerald-400 mt-1">Prior Betano 5.05 draw → +12.1% EV (<span class="abbr">SENSITIVE<span class="tooltip">SENSITIVE = The bet shows positive EV only under some assumptions (e.g. base case) but not others (conservative or aggressive); treat with caution and use smaller stakes.</span></span>; positive base/conservative). <strong><span class="abbr">SPEC<span class="tooltip">SPECULATIVE = A bet with positive expected value but more sensitive to assumptions or higher variance; smaller recommended stakes.</span></span></strong>.</div>',
        '<div class="text-xs text-emerald-400 mt-1"><span class="en">Prior Betano 5.05 draw → +12.1% EV (</span><span class="es">Previo Betano empate 5,05 → +12,1% EV (</span><span class="abbr">SENSITIVE<span class="tooltip"><span class="en">SENSITIVE = The bet shows positive EV only under some assumptions (e.g. base case) but not others (conservative or aggressive); treat with caution and use smaller stakes.</span><span class="es">SENSIBLE = La apuesta muestra EV positivo solo bajo algunos supuestos; tratar con cautela y stakes menores.</span></span></span><span class="en">; positive base/conservative).</span><span class="es">; positivo base/conservador).</span> <strong><span class="abbr">SPEC<span class="tooltip"><span class="en">SPECULATIVE = A bet with positive expected value but more sensitive to assumptions or higher variance; smaller recommended stakes.</span><span class="es">ESPECULATIVO = Apuesta con EV positivo pero más sensible a supuestos o mayor varianza; stakes recomendados menores.</span></span></span></strong>.</div>',
    ),
    (
        '<div class="p-2 bg-emerald-950/60 border border-emerald-900 rounded text-xs"><strong>Draw @5.05 (or better)</strong> — Data-aligned (AUT creator loss + JOR low-block + debut motivation + milder venue). SENSITIVE but +EV in base/cons. Small stake (S/10–12). Risks: AUT clinical despite missing pieces; JOR overperforms (quality gap limits analogy). Single failure: Alaba fitness. Conf 45%.</div>',
        '<div class="p-2 bg-emerald-950/60 border border-emerald-900 rounded text-xs"><strong><span class="en">Draw @5.05 (or better)</span><span class="es">Empate @5,05 (o mejor)</span></strong> <span class="en">— Data-aligned (AUT creator loss + JOR low-block + debut motivation + milder venue). SENSITIVE but +EV in base/cons. Small stake (S/10–12). Risks: AUT clinical despite missing pieces; JOR overperforms (quality gap limits analogy). Single failure: Alaba fitness. Conf 45%.</span><span class="es">— Alineado con datos (pérdida creador AUT + bloque bajo JOR + motivación debut + estadio más templado). SENSIBLE pero +EV en base/cons. Stake pequeño (S/10–12). Riesgos: AUT clínico pese a piezas faltantes; JOR sobreperforma (brecha de calidad limita analogía). Falla única: forma de Alaba. Conf 45%.</span></div>',
    ),
    # Classifications KSA line
    (
        '</span>: KSA-URU Under 2.5 @1.78 <span class="en">(conditions + absences align; positive conservative).</span>',
        '</span>: <span class="en">KSA-URU Under 2.5 @1.78</span><span class="es">KSA-URU Menos 2.5 @1,78</span> <span class="en">(conditions + absences align; positive conservative).</span>',
    ),
    # Sure bets table rows - abbr labels + tooltips
    (
        '<tr><td><span class="abbr">KSA-URU Under 2.5<span class="tooltip">This bet refers to choosing the event that in the Kingdom of Saudi Arabia vs Uruguay there will be 2.5 goals or less by any team in the full match (i.e., the total goals scored by both teams combined will be 0, 1, or 2).</span></span></td>',
        '<tr><td><span class="abbr"><span class="en">KSA-URU Under 2.5</span><span class="es">KSA-URU Menos 2.5</span><span class="tooltip"><span class="en">This bet refers to choosing the event that in the Kingdom of Saudi Arabia vs Uruguay there will be 2.5 goals or less by any team in the full match (i.e., the total goals scored by both teams combined will be 0, 1, or 2).</span><span class="es">Esta apuesta se refiere a elegir que en Arabia Saudita vs Uruguay habrá 2,5 goles o menos por cualquier equipo en el partido completo (es decir, el total de goles de ambos equipos combinados será 0, 1 o 2).</span></span></span></td>',
    ),
    (
        '<tr><td><span class="abbr">AUT Draw @5.05<span class="tooltip">This bet refers to choosing the event that in the Austria vs Jordan match the final score will be a draw (both teams end with the exact same number of goals, such as 0-0, 1-1, or 2-2).</span></span></td>',
        '<tr><td><span class="abbr"><span class="en">AUT Draw @5.05</span><span class="es">Empate AUT @5,05</span><span class="tooltip"><span class="en">This bet refers to choosing the event that in the Austria vs Jordan match the final score will be a draw (both teams end with the exact same number of goals, such as 0-0, 1-1, or 2-2).</span><span class="es">Esta apuesta se refiere a elegir que en el partido Austria vs Jordania el marcador final será empate (ambos equipos terminan con el mismo número de goles, como 0-0, 1-1 o 2-2).</span></span></span></td>',
    ),
    (
        '<tr><td><span class="abbr">FRA win + O3.5 (DC joint)<span class="tooltip">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span></span></td>',
        '<tr><td><span class="abbr"><span class="en">FRA win + O3.5 (DC joint)</span><span class="es">Victoria FRA + O3.5 (junta DC)</span><span class="tooltip"><span class="en">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span><span class="es">Es una apuesta combinada: Francia debe ganar el partido Y debe haber más de 3,5 goles totales (4 o más goles por ambos equipos combinados). La junta DC usa un modelo correlacionado (Dixon-Coles) en lugar de multiplicar las probabilidades separadas.</span></span></span></td>',
    ),
    # Executive summary abbr labels (duplicate instances - use replace_all where safe)
    (
        '<span class="abbr">KSA-URU Under 2.5 @1.78<span class="tooltip"><span class="en">This bet refers to choosing the event that in the Kingdom of Saudi Arabia vs Uruguay there will be 2.5 goals or less by any team in the full match (i.e., the total goals scored by both teams combined will be 0, 1, or 2).</span><span class="es">Esta apuesta se refiere a elegir que en Arabia Saudita vs Uruguay habrá 2,5 goles o menos por cualquier equipo en el partido completo (es decir, el total de goles de ambos equipos combinados será 0, 1 o 2).</span></span></span>',
        '<span class="abbr"><span class="en">KSA-URU Under 2.5 @1.78</span><span class="es">KSA-URU Menos 2.5 @1,78</span><span class="tooltip"><span class="en">This bet refers to choosing the event that in the Kingdom of Saudi Arabia vs Uruguay there will be 2.5 goals or less by any team in the full match (i.e., the total goals scored by both teams combined will be 0, 1, or 2).</span><span class="es">Esta apuesta se refiere a elegir que en Arabia Saudita vs Uruguay habrá 2,5 goles o menos por cualquier equipo en el partido completo (es decir, el total de goles de ambos equipos combinados será 0, 1 o 2).</span></span></span>',
    ),
    (
        '<span class="abbr">AUT Draw @5.05<span class="tooltip"><span class="en">This bet refers to choosing the event that in the Austria vs Jordan match the final score will be a draw (both teams end with the exact same number of goals, such as 0-0, 1-1, or 2-2).</span><span class="es">Esta apuesta se refiere a elegir que en el partido Austria vs Jordania el marcador final será empate (ambos equipos terminan con el mismo número de goles, como 0-0, 1-1 o 2-2).</span></span></span>',
        '<span class="abbr"><span class="en">AUT Draw @5.05</span><span class="es">Empate AUT @5,05</span><span class="tooltip"><span class="en">This bet refers to choosing the event that in the Austria vs Jordan match the final score will be a draw (both teams end with the exact same number of goals, such as 0-0, 1-1, or 2-2).</span><span class="es">Esta apuesta se refiere a elegir que en el partido Austria vs Jordania el marcador final será empate (ambos equipos terminan con el mismo número de goles, como 0-0, 1-1 o 2-2).</span></span></span>',
    ),
    (
        '<span class="abbr">AUT Draw<span class="tooltip"><span class="en">This bet refers to choosing the event that in the Austria vs Jordan match the final score will be a draw (both teams end with the exact same number of goals, such as 0-0, 1-1, or 2-2).</span><span class="es">Esta apuesta se refiere a elegir que en el partido Austria vs Jordania el marcador final será empate (ambos equipos terminan con el mismo número de goles, como 0-0, 1-1 o 2-2).</span></span></span>',
        '<span class="abbr"><span class="en">AUT Draw</span><span class="es">Empate AUT</span><span class="tooltip"><span class="en">This bet refers to choosing the event that in the Austria vs Jordan match the final score will be a draw (both teams end with the exact same number of goals, such as 0-0, 1-1, or 2-2).</span><span class="es">Esta apuesta se refiere a elegir que en el partido Austria vs Jordania el marcador final será empate (ambos equipos terminan con el mismo número de goles, como 0-0, 1-1 o 2-2).</span></span></span>',
    ),
    (
        '<span class="abbr">FRA win+O3.5<span class="tooltip"><span class="en">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined).</span><span class="es">Es una apuesta combinada: Francia debe ganar el partido Y debe haber más de 3,5 goles totales (4 o más goles por ambos equipos combinados).</span></span></span>',
        '<span class="abbr"><span class="en">FRA win+O3.5</span><span class="es">Victoria FRA+O3.5</span><span class="tooltip"><span class="en">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined).</span><span class="es">Es una apuesta combinada: Francia debe ganar el partido Y debe haber más de 3,5 goles totales (4 o más goles por ambos equipos combinados).</span></span></span>',
    ),
    (
        '<span class="abbr">DC FRA+O3.5 joint<span class="tooltip"><span class="en">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span><span class="es">Es una apuesta combinada: Francia debe ganar el partido Y debe haber más de 3,5 goles totales (4 o más goles por ambos equipos combinados). La junta DC significa que usamos un modelo de probabilidad correlacionada (Dixon-Coles) en lugar de simplemente multiplicar las dos probabilidades separadas.</span></span></span>',
        '<span class="abbr"><span class="en">DC FRA+O3.5 joint</span><span class="es">Junta DC FRA+O3.5</span><span class="tooltip"><span class="en">This is a combo bet: France must win the match AND there must be more than 3.5 total goals (4 or more goals by both teams combined). DC joint means we use a correlated probability model (Dixon-Coles) instead of simply multiplying the two separate chances.</span><span class="es">Es una apuesta combinada: Francia debe ganar el partido Y debe haber más de 3,5 goles totales (4 o más goles por ambos equipos combinados). La junta DC significa que usamos un modelo de probabilidad correlacionada (Dixon-Coles) en lugar de simplemente multiplicar las dos probabilidades separadas.</span></span></span>',
        True,
    ),
    # Backtest finetune arrow line (English only in en span - check)
    (
        '<span class="text-slate-400">→ Much better calibration for realized 0-0 and similar opener/minnow shocks (2002 FRA-SEN precedent).</span></span>',
        '<span class="text-slate-400"><span class="en">→ Much better calibration for realized 0-0 and similar opener/minnow shocks (2002 FRA-SEN precedent).</span><span class="es">→ Mucho mejor calibración para el 0-0 real y shocks similares de apertura/minnow (precedente FRA-SEN 2002).</span></span></span>',
    ),
]


def main():
    html = REPORT.read_text(encoding='utf-8')
    n = 0
    for item in REPLACEMENTS:
        replace_all = item[2] if len(item) > 2 else False
        old, new = item[0], item[1]
        if old not in html:
            print(f"WARN missing: {old[:70]}...")
            continue
        if replace_all:
            count = html.count(old)
            html = html.replace(old, new)
            n += count
        else:
            html = html.replace(old, new, 1)
            n += 1
    REPORT.write_text(html, encoding='utf-8')
    print(f"Applied {n} replacements")


if __name__ == '__main__':
    main()